// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditorcore[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditorcore.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.core</name>"
"        <implementation>EditorManager</implementation>"
"        <description>Crystal Space Editor Core System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef EditorManager_FACTORY_REGISTER_DEFINED 
  #define EditorManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(EditorManager) 
  #endif

class cseditorcore
{
SCF_REGISTER_STATIC_LIBRARY(cseditorcore,metainfo_cseditorcore)
  #ifndef EditorManager_FACTORY_REGISTERED 
  #define EditorManager_FACTORY_REGISTERED 
    EditorManager_StaticInit EditorManager_static_init__; 
  #endif
public:
 cseditorcore();
};
cseditorcore::cseditorcore() {}

}
