// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditorspaces[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditorspaces.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.space.3dview</name>"
"        <implementation>CS3DSpace</implementation>"
"        <description>3D View</description>"
"        <allowMultiple>false</allowMultiple>"
"      </class>"
"      <class>"
"        <name>crystalspace.editor.space.properties</name>"
"        <implementation>PropertiesSpace</implementation>"
"        <description>Properties</description>"
"        <allowMultiple>true</allowMultiple>"
"      </class>"
"      <class>"
"        <name>crystalspace.editor.space.scenetree</name>"
"        <implementation>SceneTree</implementation>"
"        <description>Scene</description>"
"        <allowMultiple>true</allowMultiple>"
"      </class>"
"      <class>"
"        <name>crystalspace.editor.space.textlog</name>"
"        <implementation>TextLog</implementation>"
"        <description>Logs</description>"
"        <allowMultiple>true</allowMultiple>"
"      </class>"
"      <class>"
"	<name>crystalspace.editor.space.partedit</name>"
"	<implementation>CSPartEditSpace</implementation>"
"	<description>Particles</description>"
"	<allowMultiple>true</allowMultiple>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CS3DSpace_FACTORY_REGISTER_DEFINED 
  #define CS3DSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CS3DSpace) 
  #endif
  #ifndef PropertiesSpace_FACTORY_REGISTER_DEFINED 
  #define PropertiesSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(PropertiesSpace) 
  #endif
  #ifndef SceneTree_FACTORY_REGISTER_DEFINED 
  #define SceneTree_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SceneTree) 
  #endif
  #ifndef TextLog_FACTORY_REGISTER_DEFINED 
  #define TextLog_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(TextLog) 
  #endif
  #ifndef CSPartEditSpace_FACTORY_REGISTER_DEFINED 
  #define CSPartEditSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CSPartEditSpace) 
  #endif

class cseditorspaces
{
SCF_REGISTER_STATIC_LIBRARY(cseditorspaces,metainfo_cseditorspaces)
  #ifndef CS3DSpace_FACTORY_REGISTERED 
  #define CS3DSpace_FACTORY_REGISTERED 
    CS3DSpace_StaticInit CS3DSpace_static_init__; 
  #endif
  #ifndef PropertiesSpace_FACTORY_REGISTERED 
  #define PropertiesSpace_FACTORY_REGISTERED 
    PropertiesSpace_StaticInit PropertiesSpace_static_init__; 
  #endif
  #ifndef SceneTree_FACTORY_REGISTERED 
  #define SceneTree_FACTORY_REGISTERED 
    SceneTree_StaticInit SceneTree_static_init__; 
  #endif
  #ifndef TextLog_FACTORY_REGISTERED 
  #define TextLog_FACTORY_REGISTERED 
    TextLog_StaticInit TextLog_static_init__; 
  #endif
  #ifndef CSPartEditSpace_FACTORY_REGISTERED 
  #define CSPartEditSpace_FACTORY_REGISTERED 
    CSPartEditSpace_StaticInit CSPartEditSpace_static_init__; 
  #endif
public:
 cseditorspaces();
};
cseditorspaces::cseditorspaces() {}

}
