// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_cseditor_static_plugins
{
  _Bind_cseditor_static_plugins ();
};
namespace { _Bind_cseditor_static_plugins bind_cseditor_static_plugins; }

