// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditormenus[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditormenus.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.menu.3dmenu</name>"
"        <implementation>CS3DMenu</implementation>"
"        <description>3D View menu</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CS3DMenu_FACTORY_REGISTER_DEFINED 
  #define CS3DMenu_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CS3DMenu) 
  #endif

class cseditormenus
{
SCF_REGISTER_STATIC_LIBRARY(cseditormenus,metainfo_cseditormenus)
  #ifndef CS3DMenu_FACTORY_REGISTERED 
  #define CS3DMenu_FACTORY_REGISTERED 
    CS3DMenu_StaticInit CS3DMenu_static_init__; 
  #endif
public:
 cseditormenus();
};
cseditormenus::cseditormenus() {}

}
