// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditorheaders[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditorheaders.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.header.3dheader</name>"
"        <implementation>CS3DHeader</implementation>"
"        <description>3D View Header</description>"
"        <space>crystalspace.editor.space.3dview</space>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CS3DHeader_FACTORY_REGISTER_DEFINED 
  #define CS3DHeader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CS3DHeader) 
  #endif

class cseditorheaders
{
SCF_REGISTER_STATIC_LIBRARY(cseditorheaders,metainfo_cseditorheaders)
  #ifndef CS3DHeader_FACTORY_REGISTERED 
  #define CS3DHeader_FACTORY_REGISTERED 
    CS3DHeader_StaticInit CS3DHeader_static_init__; 
  #endif
public:
 cseditorheaders();
};
cseditorheaders::cseditorheaders() {}

}
